apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app   : my-k8s-web-app
    owner : Jeka4el
spec:
  replicas: 3
  selector:
    matchLabels:
      project: first-rep
  template:
    metadata:
      labels:
        project: first-rep
    spec:
      containers:
        - name: first-web
          image: jeka4el/k8s-nginx:latest
          ports:
            - containerPort: 80


