apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas-autoscale
  labels:
    app   : my-k8s-web-app
    owner : Jeka4el
spec:
  replicas: 2
  selector:
    matchLabels:
      project: first-rep-scale
  template:
    metadata:
      labels:
        project: first-rep-scale
    spec:
      containers:
        - name: first-web
          image: jeka4el/k8s-nginx:v1
          ports:
            - containerPort: 80

--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-replicas-autoscale # The name of my deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

