apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    name: myapp
    env : prod
    owener : Jeka4el
spec:
  containers:
  - name: contaoner-nginx
    image: jeka4el/k8s-nginx:latest
    ports:
      - containerPort: 80
